### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by blueelvis**
Update `start:dev` script to run Functions V1 runtime and then run all the functions present inside the `dist` folder.

@maxnorth - The runtime which is being targetted by default by the seed project is v2. This fixes the script to run according to v1.

### CODE REVIEW

**Review by maxnorth — CHANGES_REQUESTED** [review]
Can you add the cli tool to devDependencies with the expected version locked down.

**Comment by blueelvis** [comment]
Need to check on that whether just including the cli in a dev dependency
will work or not because as per installation instructions, the cli needs to
be installed using npm globally (-g).

Let me check and then get back to you.

**Comment by blueelvis** [comment]
@maxnorth - I have added the `azure-functions-core-tools` as a dev dependency. I have also added the `botbuilder-azure` dependency which is needed to keep track of conversation state in Cosmos.

**Comment by maxnorth** [comment]
In our wire-framing meeting with Dale and Dan, we agreed to use the v2 runtime of azure functions because this will support linux and on premise runtime. Although it is still in preview, Microsoft has announced that GA for 2.0 is coming soon and that they have no more planned breaking change updates after this month. https://twitter.com/AzureFunctions/status/1029148907974979584

Additionally, once 2.0 rolls out, support for 1.0 is only guaranteed for a year, so we should get ahead of the curve to avoid having to update later on.

@danbjoseph and @dalekunce can you affirm once again that we are good to continue with v2 azure functions?

**Comment by dalekunce** [comment]
I confirm the choice of v2.

**Comment by blueelvis** [comment]
Alright. Let me roll a commit to use v2 instead and make any required changes as well.

**Comment by blueelvis** [comment]
@maxnorth - I just pushed out a commit to use the latest runtime. Could you please check once and then approve this PR?

**Review by maxnorth — APPROVED** [review]

**Pull request merged**
