### PR TITLE
Create issue_template.md

### PR DESCRIPTION
**Pull request by m4thfr34k**
Proposed template for issues

### CODE REVIEW

**Comment by maxnorth** [comment]
I like the proposed template for feature requests, but we should [use this setup](https://help.github.com/articles/creating-issue-templates-for-your-repository/) so that we can have multiple issue types, including bug reports. This will also put the template into a special .github folder so they are kept separate from the main project code.

**Comment by maxnorth** [comment]
Here's a good bug report template we can use: https://gist.github.com/carlo/3402842

**Review by maxnorth — CHANGES_REQUESTED** [review]
Comments listed above

**Comment by m4thfr34k** [comment]
Completely agree with adding these templates as per the GitHub setup instructions and having different templates depending on issue type.

**Comment by m4thfr34k** [comment]
Closing this PR without merging. Issue template will be created using the Issue Template Builder.

**Pull request closed without merging**
