### PR TITLE
Data Flow diagram

### PR DESCRIPTION
**Pull request by m4thfr34k**
Data Flow diagram for the chat bot and admin SPA

### CODE REVIEW

**Review by blueelvis — COMMENTED** [review]
Are we going to use the same Red Cross auth for Admin Web Apps? Or is there some other authentication?

cc: @maxnorth

**Comment by maxnorth** [comment]
Yep, same auth for the web app, regardless of dashboard users and admin users

**Comment by m4thfr34k** [comment]
Data Flow diagram updated to reflect Red Cross AUTH for the SPA in addition to the bot channels.

**Comment by blueelvis** [comment]
@m4thfr34k - This looks good. Merging the PR now.

**Review by blueelvis — APPROVED** [review]
Approved

**Pull request merged**
