### PR TITLE
Infrastructure deployment code

### PR DESCRIPTION
**Pull request by blueelvis**
I have added some ARM templates and Powershell scripts in the `Deploy` folder. 

There are scripts to deploy the following -

1. Azure Cosmos DB (Collections need to be created manually as of now)
2. Azure Storage Account
3. Azure Web Apps (With support to provision multiple web apps in an app service plan)

Please let me know if you have any suggestions for improvement :)

### CODE REVIEW

**Comment by maxnorth** [comment]
Hey @blueelvis, gathering my comments/questions here as I review:

1) Are these scripts in a place where they could potentially be run in CI/CD, or would they still need work refactoring them?
2) Do we know if these scripts are compatible with powershell core and can be executed on Travis' linux environment? Have we tested them?
3) Seems like there are a few places where some things are passed as arguments to the script that we should really hard-code into the template. For instance, we should never need to specify the Cosmos API type in a deploy, this is more of a decided architectural choice.

**Comment by blueelvis** [comment]
@maxnorth Please find the answers below -

1. I don't think that running these scripts during each build is necessary since they are only for infrastructure deployment. Doing this during CI/CD means that we have to tear down the current infrastructure, build it new and then configure it (Things like app settings etc)
2. See (1). Not required.
3. There seems to be different sets of parameters required for other API Types for CosmosDB deployments. Check [this](https://github.com/Azure/azure-quickstart-templates/blob/06f289dd45c5bcd625207f766592119acc44973e/101-cosmosdb-create-arm-template/azuredeploy.json#L40) & [this](https://github.com/Azure/azure-quickstart-templates/blob/06f289dd45c5bcd625207f766592119acc44973e/101-cosmosdb-create-arm-template/azuredeploy.json#L58). I decided to stick to these because these should be the most utilized api types.

**Comment by maxnorth** [comment]
Wouldn't need to tear down, you can do an incremental deploy with an arm template instead of a full replace.

One other point: can we have the deployments be configuration-driven by reading the values out of a file? Ideally the deployment parameters for the infrastructure and the runtime application should be kept in one shared location.

**Comment by blueelvis** [comment]
@maxnorth - That definitely makes sense. I was thinking that for Red Cross environments, we could have an additional wrapper script on top of this (Because of naming conventions, tagging etc). We cannot get a complete set of scripts for end to end deployments till the time the App is actually in use because then we have to configure other settings like Application Settings, Connection Strings etc. We can definitely have that as well.


The scripts included in this PR are more generic in nature as in if someone else wants to deploy the infrastructure, then they can follow their own naming conventions (if any) and then start with the bot.


We obviously have to target that as well so that deployments for Red Cross are as automated as possible. That can be targeted in future PRs. What do you think?

**Comment by maxnorth** [comment]
Ok, that sounds good, i'm alright if we revisit.

**Review by maxnorth — APPROVED** [review]

**Pull request merged**
